version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: us_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: usuariosMS
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  usuario:
    build: .
    container_name: usuario_ms
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mysql
      DB_NAME: usuariosMS
    depends_on:
      - db
