global:
  scrape_interval: 15s

scrape_configs:
  # ──────────────────────────────────────────────
  # 1) Todos los microservicios con endpoint /metrics
  # ──────────────────────────────────────────────
  - job_name: 'microservicios'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'usuario_ms:3000'
          - 'reservas_ms:3000'
          - 'propiedades_ms:3000'
          - 'pagos_ms:3000'

  # ──────────────────────────────────────────────
  # 2) HAProxy stats en CSV con basic_auth
  # ──────────────────────────────────────────────
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy-exporter:9101']

  - job_name: 'spark-master'
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['spark-master:8082']

  - job_name: 'spark-worker'
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['spark-worker:8081']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    # (opcional: usa kafka_exporter si lo tuvieras)
