version: '3.8'
services:
  usuario-ms:
    build: .
    container_name: usuario-ms
    ports:
      - "3001:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: mysql
      DB_NAME: usuariosMS
      PORT: 3000
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2  # alta disponibilidad
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8.0
    container_name: usuario-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: usuariosMS
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 5

volumes:
  mysql_data:
